--------------CREATE A TRIGGER------------------------------
CREATE OR ALTER TRIGGER PCL_PURCHASEORDER_AU2 FOR PCL_PURCHASEORDER
ACTIVE AFTER UPDATE POSITION 0
AS
DECLARE VARIABLE HARGABARU NUMERIC(15,3);
DECLARE VARIABLE IDBARANGMERK VARCHAR(15);
BEGIN
    IF (UPDATING AND OLD.APPROVEREV = 'N' AND NEW.APPROVEREV = 'Y') THEN
    BEGIN
        FOR SELECT HARGA, IDBARANGMERK FROM PCL_PURCHASEORDERITEM WHERE IDPO = NEW.IDPO
        INTO :HARGABARU, :IDBARANGMERK
        DO
        BEGIN
           UPDATE WHS_STOCKINITEM SET HARGAPO = :HARGABARU, IDBARANGMERK = :IDBARANGMERK
           WHERE IDPO = NEW.IDPO AND IDBARANGMERK = :IDBARANGMERK;
        END
    END
END


-----------ALTER TABLE AND ADD NEW COLUMN--------------------------
ALTER TABLE PCL_PURCHASEORDER ADD NPKAPPROVEREV CHAR(5)
ALTER TABLE PCL_PURCHASEORDER ADD DATEAPPROVEREV TIMESTAMP
ALTER TABLE PCL_PURCHASEORDER ADD NPKCHECKREV CHAR(5)
ALTER TABLE PCL_PURCHASEORDER ADD DATECHECKREV TIMESTAMP
ALTER TABLE PCL_PURCHASEORDER ADD NPKPREPAREREV CHAR(5)
ALTER TABLE PCL_PURCHASEORDER ADD DATEPREPAREREV TIMESTAMP
ALTER TABLE PCL_PURCHASEORDER ADD APPROVEREV CHAR(1)
ALTER TABLE PCL_PURCHASEORDER ADD PREPAREREV CHAR(1)
ALTER TABLE PCL_PURCHASEORDER ADD CHECKREV CHAR(1)
