CREATE OR ALTER TRIGGER PCL_PURCHASEORDER_AU2 FOR PCL_PURCHASEORDER
ACTIVE AFTER UPDATE POSITION 0
AS
DECLARE VARIABLE HARGABARU NUMERIC(15,3);
DECLARE VARIABLE IDBARANGMERK VARCHAR(15);
BEGIN
    IF (UPDATING AND OLD.APPROVEREV = 'N' AND NEW.APPROVEREV = 'Y') THEN
    BEGIN
        FOR SELECT HARGA, IDBARANGMERK FROM PCL_PURCHASEORDERITEM WHERE IDPO = NEW.IDPO
        INTO :HARGABARU, :IDBARANGMERK
        DO
        BEGIN
           UPDATE WHS_STOCKINITEM SET HARGAPO = :HARGABARU, IDBARANGMERK = :IDBARANGMERK
           WHERE IDPO = NEW.IDPO AND IDBARANGMERK = :IDBARANGMERK;
        END
    END
END
