SELECT
  A.IDPO, A.IDPR, NOADJUST, TANGGALPO, A.IDSUPPLIER, FPPN, JUMLAHPO, DISCAMOUNT,
  DISCPERCENT, IDTOP, FKLC, TOPDESC, TGLDELIVERY, A.IDCURRENCY, SISANILAI, DECBLAIN,
  BLAIN, DAYS, REVNO, REVDATE, LASTBPB, VOUCHER, TANGGALENTRI, FCANCEL, ADJCODE,
  REMARKS, FCOPY, A.WHSCODE, PENALTY, FHABIS, DICOPY, NOPOOLD, SETUP, TOPNOTES,
  PAYMENT, DP, YBI, KOMPENSASI, NOCOM, SELISIH, SALDOSLH, NILAIACC, TARIKACC,
  APCLOSE, FBEBASPPN, TYBC, NOFORMD, TAHUNHS, NOHS, FSTOCKCODE, FAPPROVE,
  APPROVEDATE, A.USERNAME, A.TGLINPUT, TNOPPN, SNOPPN, JSPR, NP8P, FESTIMASI,
  FPOJASA, A.KODEASALINPUT, A.FLOCALIMPORT, B.NAMA AS NAMA_VENDOR,
  NPKAPPROVEREAL, DATEAPPROVEREAL, APPROVEDIR, NPKPREPAREREV, DATEPREPAREREV,
  PREPAREREV, NPKCHECKREV, DATECHECKREV, CHECKREV, NPKAPPROVEREV, DATEAPPROVEREV, APPROVEREV,
  FMATSPAREPART, FPPNPBBKB, PPNPBBKB, D.TGLSTOCKIN, C.IDBARANGMERK, C.HARGA, D.PROSESACC,
  APPROVEZA, DATEAPPROVEZA, APPROVEAT, DATEAPPROVEAT ,APPROVEIK, DATEAPPROVEIK, 
  APPROVEAT, DATEAPPROVEAT, APPROVEZA, DATEAPPROVEZA
FROM
  PCL_PURCHASEORDER A
  LEFT JOIN PCL_REFSUPPLIER B ON (B.IDSUPPLIER=A.IDSUPPLIER)
  LEFT JOIN PCL_PURCHASEORDERITEM C ON (C.IDPO=A.IDPO)
  LEFT JOIN WHS_STOCKIN D ON (D.IDPO=A.IDPO)
WHERE
  (B.NAMA LIKE 'NON%') --- SYARAT UNTUK VENDOR NFU
  AND
  (C.HARGA = 1)      --- SYARAT UNTUK HARGA BARANG = 1
  AND
  (COALESCE(A.FAPPROVE, 'N')='N') -- 22-12-2021 JIKA SUDAH DIAPPROVE, GAK BISA REVISI, UNAPPROVE DULU
  AND
  (D.PROSESACC <> 'Y') --- SYARAT BELUM DITARIK OLEH ACCOUNTING
  AND
  EXTRACT(MONTH FROM D.TGLSTOCKIN) = EXTRACT(MONTH FROM TANGGALPO)
  AND
  EXTRACT(MONTH FROM D.TGLSTOCKIN) = EXTRACT(MONTH FROM CURRENT_DATE)
  AND
  EXTRACT(YEAR FROM D.TGLSTOCKIN) = EXTRACT(YEAR FROM CURRENT_DATE)
  AND
  NOT EXISTS (SELECT 1 FROM WHS_STOCKIN E LEFT JOIN WHS_STOCKINITEM F ON (E.IDSTOCKIN=F.IDSTOCKIN)
              WHERE D.IDPO=E.IDPO
              AND EXTRACT(MONTH FROM E.TGLSTOCKIN) =  EXTRACT(MONTH FROM DATEADD(MONTH, -1, CURRENT_DATE))
              AND EXTRACT(YEAR FROM E.TGLSTOCKIN) = EXTRACT(YEAR FROM CURRENT_DATE)
              AND F.IDBARANGMERK=C.IDBARANGMERK)
