SELECT
  A.IDPO, A.IDPR, NOADJUST, TANGGALPO, A.IDSUPPLIER, FPPN, JUMLAHPO, DISCAMOUNT,
  DISCPERCENT, IDTOP, FKLC, TOPDESC, TGLDELIVERY, A.IDCURRENCY, SISANILAI, DECBLAIN,
  BLAIN, DAYS, REVNO, REVDATE, LASTBPB, VOUCHER, TANGGALENTRI, FCANCEL, ADJCODE,
  REMARKS, FCOPY, A.WHSCODE, PENALTY, FHABIS, DICOPY, NOPOOLD, SETUP, TOPNOTES,
  PAYMENT, DP, YBI, KOMPENSASI, NOCOM, SELISIH, SALDOSLH, NILAIACC, TARIKACC,
  APCLOSE, FBEBASPPN, TYBC, NOFORMD, TAHUNHS, NOHS, FSTOCKCODE, FAPPROVE,
  APPROVEDATE, A.USERNAME, A.TGLINPUT, TNOPPN, SNOPPN, JSPR, NP8P, FESTIMASI,
  FPOJASA, A.KODEASALINPUT, A.FLOCALIMPORT, B.NAMA AS NAMA_VENDOR,
  NPKAPPROVEREAL, DATEAPPROVEREAL, APPROVEDIR, NPKPREPAREREV, DATEPREPAREREV,
  PREPAREREV, NPKCHECKREV, DATECHECKREV, CHECKREV, NPKAPPROVEREV, DATEAPPROVEREV, APPROVEREV
  FMATSPAREPART, FPPNPBBKB, PPNPBBKB, D.TGLSTOCKIN, C.IDBARANGMERK, C.HARGA, D.PROSESACC
FROM
  PCL_PURCHASEORDER A
  LEFT JOIN PCL_REFSUPPLIER B ON (B.IDSUPPLIER=A.IDSUPPLIER)
  LEFT JOIN PCL_PURCHASEORDERITEM C ON (C.IDPO=A.IDPO)
  LEFT JOIN WHS_STOCKIN D ON (D.IDPO=A.IDPO)
WHERE
  (B.NAMA LIKE 'NON%') --- SYARAT UNTUK VENDOR NFU
  AND
  (C.HARGA = 1)      --- SYARAT UNTUK HARGA BARANG = 1
  AND
  (D.PROSESACC <> 'Y') --- SYARAT BELUM DITARIK OLEH ACCOUNTING
  AND
  EXTRACT(DAY FROM D.TGLSTOCKIN) >= 1 AND EXTRACT(DAY FROM D.TGLSTOCKIN) <= 5 ---SYARAT UNTUK TGL BPB 1-5
  AND
  C.IDBARANGMERK <>    --- SYARAT TIDAK BOLEH ADA BPB PADA BULAN SEBELUMNYA UNTUK BARANG YANG SAMA
    (SELECT I.IDBARANGMERK
    FROM PCL_PURCHASEORDERITEM I
    LEFT JOIN WHS_STOCKIN J ON (I.IDPO=J.IDPO)
    WHERE --J.TGLSTOCKIN IS NULL AND 
    EXTRACT(MONTH FROM J.TGLSTOCKIN) =  EXTRACT(MONTH FROM DATEADD(MONTH, -1, CURRENT_DATE))
    AND EXTRACT(YEAR FROM J.TGLSTOCKIN) = EXTRACT(YEAR FROM CURRENT_DATE))
