SELECT COUNT(*)
FROM SLE_DELIVERYORDER A
LEFT JOIN SLE_SURATJALAN B ON (A.NODO = B.NODO)
WHERE A.STUFFING = CURRENT_DATE AND B.NOSJ IS NULL AND
(KONFIRMSTUFFING <> 'Y' OR NOT EXISTS (SELECT 1
                        FROM SLE_DELIVERYORDER A
                        LEFT JOIN SLE_CHANGELOADING B ON (A.NODO = B.NODO)
                        WHERE REVISIDATE IS NOT NULL AND REVISIDATE = CURRENT_DATE
                        GROUP BY A.NODO, STUFFING
                        HAVING MAX(REVISIDATE) > STUFFING))
GROUP BY A.STUFFING
