-----CREATING VIEW FOR SHOW DATA REQUEST-----
CREATE OR ALTER VIEW PO_RPT_SISAPO(
    IDPO,
    IDVOUCHER,
    IDPR,
    IDBUDGET,
    IDPROYEK,
    TANGGALPO,
    TGLACC,
    JUMLAHPO,
    NILAIVOUCHER,
    IDCURRENCY)
AS
SELECT D.IDPO, E.IDVOUCHER, C.IDPR, B.IDBUDGET, B.IDPROYEK, D.TANGGALPO, F.TGLACC,
       D.JUMLAHPO, E.NILAI, D.IDCURRENCY
FROM PRO_KIPIASSETPROYEK B
LEFT JOIN PCL_PRPURCHASE C ON (B.IDPROYEK = C.IDPROYEK)
LEFT JOIN PCL_PURCHASEORDER D ON (C.IDPR = D.IDPR)
LEFT JOIN FIX_VOUCHERITEM E ON (D.IDPO = E.IDPO)
LEFT JOIN FIX_VOUCHERHEADER F ON (E.IDVOUCHER = F.IDVOUCHER)
     AND (E.VOUCHERTYPE =F.VOUCHERTYPE)
     AND (E.IDBANKNOREK = F.IDBANKNOREK)
WHERE --B.IDBUDGET IN (SELECT * FROM FY_2022_TMP)
     --D.TANGGALPO >= '01.04.2022' AND D.TANGGALPO <= '31.03.2023'
     TGLACC < '31.03.2023'
     AND (D.JUMLAHPO - E.NILAI) <> 0 AND (D.JUMLAHPO - E.NILAI) IS NOT NULL

UNION ALL

SELECT D.IDPO, E.IDVOUCHER, C.IDPR, B.IDBUDGET, B.IDPROYEK, D.TANGGALPO, F.TGLACC,
       D.JUMLAHPO, E.NILAI, D.IDCURRENCY
FROM PRO_KIPIASSETPROYEK B
LEFT JOIN PCL_PRPURCHASE C ON (B.IDPROYEK = C.IDPROYEK)
LEFT JOIN PCI_PURCHASEORDER D ON (C.IDPR = D.IDPR)
LEFT JOIN FIX_VOUCHERITEM E ON (D.IDPO = E.IDPO)
LEFT JOIN FIX_VOUCHERHEADER F ON (E.IDVOUCHER = F.IDVOUCHER)
     AND (E.VOUCHERTYPE =F.VOUCHERTYPE)
     AND (E.IDBANKNOREK = F.IDBANKNOREK)
WHERE --B.IDBUDGET IN (SELECT * FROM FY_2022_TMP)
     --D.TANGGALPO >= '01.04.2022' AND D.TANGGALPO <= '31.03.2023'
     TGLACC < '31.03.2023'
     AND (D.JUMLAHPO - E.NILAI) <> 0 AND (D.JUMLAHPO - E.NILAI) IS NOT NULL

-----CREATING PROCEDURE FOR CALL MORE SPECIFIC-----
CREATE OR ALTER PROCEDURE PO_RESUME_V1(
    TAHUN1 INTEGER,
    TAHUN2 INTEGER)
RETURNS (
    I integer, 
    IDBUDGET VARCHAR(10),
    IDPROYEK VARCHAR(20),
    IDPR VARCHAR(15),
    IDPO VARCHAR(10),
    JUMLAHPO DOUBLE PRECISION,
    IDVOUCHER VARCHAR(8),
    NILAIVOUCHER DOUBLE PRECISION,
    IDCURRENCY VARCHAR(3),
    TANGGALPO DATE)
AS
DECLARE VARIABLE VNOPO VARCHAR(10);
DECLARE VARIABLE VNOVOUCHER VARCHAR(8);
DECLARE VARIABLE VNOPR VARCHAR(15);
DECLARE VARIABLE VKODE VARCHAR(10);
DECLARE VARIABLE VKD_PROYEK VARCHAR(20);
DECLARE VARIABLE VNILAIPO DOUBLE PRECISION;
DECLARE VARIABLE VNILAIVOUCHER DOUBLE PRECISION;
DECLARE VARIABLE VCURRENCY VARCHAR(3);
DECLARE VARIABLE VTANGGALPO DATE;
DECLARE VARIABLE OLD_KODE VARCHAR(10);
DECLARE VARIABLE OLD_NOPO VARCHAR(10);
DECLARE VARIABLE OLD_KD_PROYEK VARCHAR(20);
DECLARE VARIABLE OLD_JUMLAHPO DOUBLE PRECISION;
DECLARE VARIABLE OLD_NOPR VARCHAR(15);
BEGIN
  I=0;OLD_KODE=NULL;OLD_KD_PROYEK=NULL;OLD_NOPO=NULL;OLD_NOPR=NULL;
  FOR SELECT
    A.IDBUDGET, A.IDPROYEK, A.IDPR, A.IDPO, A.JUMLAHPO, A.IDVOUCHER,
    A.NILAIVOUCHER, A.IDCURRENCY, A.TANGGALPO
  FROM PO_RPT_SISAPO_V1 A
  WHERE EXTRACT(YEAR FROM A.TANGGALPO) >= :TAHUN1 AND EXTRACT(YEAR FROM A.TANGGALPO) <= :TAHUN2
    INTO :VKODE, :VKD_PROYEK, :VNOPR, :VNOPO, :VNILAIPO, :VNOVOUCHER, :VNILAIVOUCHER,
    :VCURRENCY, :VTANGGALPO
  DO BEGIN
    I=:I+1;
    IF (COALESCE(OLD_KODE,'') <> VKODE) THEN
    BEGIN
      OLD_KODE=:VKODE; --OLD_KD_PROYEK=:VKD_PROYEK;
      IDBUDGET=:VKODE;     --IDPROYEK=:VKD_PROYEK;
      IF (COALESCE(OLD_KD_PROYEK,'') <> VKD_PROYEK) THEN
      BEGIN
        OLD_KD_PROYEK=:VKD_PROYEK;
        IDPROYEK=:VKD_PROYEK;
      END
      ELSE BEGIN
        IDPROYEK=NULL;
      END
    END
    ELSE BEGIN
    IDBUDGET=NULL; --IDPROYEK=NULL;
      IF (COALESCE(OLD_KD_PROYEK,'') <> VKD_PROYEK) THEN
      BEGIN
        OLD_KD_PROYEK=:VKD_PROYEK;
        IDPROYEK=:VKD_PROYEK;
      END
      ELSE BEGIN
        IDPROYEK=NULL;
      END
    END

    IF (COALESCE(OLD_NOPR,'') <> VNOPR) THEN
    BEGIN
      OLD_NOPR=:VNOPR;
          IDPR=:VNOPR;
      IF (COALESCE(OLD_NOPO,'') <> VNOPO) THEN
      BEGIN
        OLD_NOPO=:VNOPO; OLD_JUMLAHPO=:VNILAIPO;
        IDPO=:VNOPO;     JUMLAHPO=:VNILAIPO;
      END
      ELSE BEGIN
        IDPO=VNOPO; JUMLAHPO=NULL;
      END
    END
    ELSE BEGIN
      IDPR=NULL;
      IF (COALESCE(OLD_NOPO,'') <> VNOPO) THEN
      BEGIN
        OLD_NOPO=:VNOPO; OLD_JUMLAHPO=:VNILAIPO;
        IDPO=:VNOPO;     JUMLAHPO=:VNILAIPO;
      END
      ELSE BEGIN
        IDPO=NULL; JUMLAHPO=NULL;
      END
    END
    IDVOUCHER =: VNOVOUCHER; NILAIVOUCHER =: VNILAIVOUCHER; IDCURRENCY =: VCURRENCY; TANGGALPO =: VTANGGALPO;
    SUSPEND;
  END
END

-----AGGREGATING SOME VALUE FROM THE PROCEDURE-----
SELECT IDBUDGET, SUM(JUMLAHPO) AS NILAIPO,
SUM(NILAIVOUCHER) AS NILAIVOUCHER,
(SUM(JUMLAHPO) - SUM(NILAIVOUCHER)) AS NILAISISA, IDCURRENCY
FROM PO_RESUME(:TAHUN1, :TAHUN2)
WHERE IDBUDGET IN (SELECT * FROM FY_2022_TMP) AND
      TANGGALPO >= '01.04.2022' AND TANGGALPO <= '31.03.2023'
GROUP BY IDBUDGET, IDCURRENCY
